### ISSUE TITLE
How to detect the Junk E-mail folder

### ISSUE THREAD

**Issue by ArchieCoder** [OfficeDev/O365-Win-Snippets#10]
We are developing an email client that relies on the ActiveSync protocol. In short, we have facing a big issue on how to detect the “Junk E-mail” folder. The main issue is the ActiveSync protocol returns the folder type 12 which is considered as a User Folder. Microsoft confirmed that it is like that (https://social.msdn.microsoft.com/Forums/en-US/e6103451-12bc-4ca7-a3bf-1046c261ac97/how-can-we-detect-that-the-junk-email-junk-email-rss-feeds-sync-issues-conflicts?forum=os_exchangeprotocols#d97b363f-0664-466c-9730-e0a327bcf94a). The main issue is when a client uses a non-English system or email server, the Folder will be called something else. On Outlook Desktop or O365, this folder is detected correctly and we can’t do a delete. How do they know?

I installed the O365-Win-Snippets and the Office 365 don’t provide a way to know if it is a system or user folder. It returns a string DisplayName which is not helpful.

                 
If you happen to know the magic, it would be nice! Also, I think the IFolder should provide the Folder type.

Thank you

FYI: I tried to reach via your email officedev@microsoft.com, but the server returns me:
Your message couldn't be delivered because the group you're sending to needs to know who you are before it will accept your message.
To fix this problem, ask the email admin for the group to configure the group to accept messages from you.

**Comment by MIchaelMainer** [comment]
@ArchieCoder 

Thank you for contacting us. This repo is specific to the Office 365 REST API snippets. It doesn't contain any sample code about ActiveSync. The Exchange Protocol forum is the appropriate place to raise this issue (as you've already done). I'll go ahead and close this issue with this in mind.

With that said, I'll tell you what I'd do if I wasn't satisfied with the response in the forum. 
* I'd suggest you install MFCMapi and inspect all the properties set on the default folders. This would be the best way to investigate whether there are any properties that may hint to whether they are default folders. 
* Another option is to figure out a dummy request that will expect to fail against a default folder. For example, I'd try to use the MoveFolder operation. I'd expect that to fail for default folders. Or, if you try to rename a default folder, that might fail. I'm not sure whether the default folder names are reserved (Outlook client doesn't let me create a folder with the name of a default folder, but the service might), so I may try to create a dummy folder with the same name of a folder as a test to see if it is default (assuming the service reserves those names).

I know that these are not optimal solutions that require you to revert state. This is where I'd start my fishing expedition for a solution.

**Comment by ArchieCoder** [comment]
Thanks for the hints it is appreciated.
